import React from 'react';
import { Link } from 'react-router-dom';

const GhostWorkoutTerms: React.FC = () => {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-12">
          <h1 className="text-3xl font-extrabold text-gray-900 sm:text-4xl">
            Terms of Service
          </h1>
          <p className="mt-4 text-lg text-gray-500">
            Last Updated: May 11, 2026
          </p>
        </div>

        <div className="bg-white shadow overflow-hidden sm:rounded-lg">
          <div className="px-4 py-5 sm:p-6">
            <div className="space-y-8">

              {/* 1 */}
              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">1. Introduction</h2>
                <p className="text-gray-700 mb-4">
                  Welcome to Ghost Workout ("Service"). These Terms of Service ("Terms") govern your use of the Service operated by Hello Favors, LLC ("we," "us," or "our"), including our website at ghostworkout.com and our mobile application.
                </p>
                <p className="text-gray-700">
                  By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the Terms, you may not access or use the Service.
                </p>
              </section>

              {/* 2 */}
              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">2. Description of Service</h2>
                <p className="text-gray-700 mb-4">
                  Ghost Workout is a fitness tracking application for running and walking. The Service includes:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-4">
                  <li>GPS-based outdoor workout recording, including route mapping, distance, pace, and duration</li>
                  <li>Indoor workout recording using device pedometer and step-based distance estimation</li>
                  <li>Ghost comparison and replay — comparing a current workout against a prior recorded workout of your own</li>
                  <li>Workout history, route storage, and cross-device sync via your account</li>
                  <li>Premium AI Reflection — a short, post-workout reflection generated by an AI model based on a structured summary of your completed workout (premium subscription required)</li>
                </ul>
                <div className="bg-amber-50 border-l-4 border-amber-400 p-4">
                  <p className="text-amber-800">
                    <span className="font-semibold">Important:</span> Ghost Workout is a fitness tracking tool, not a medical, clinical, or professional coaching service. Nothing in the Service constitutes medical, nutritional, or professional fitness advice. Always consult a qualified healthcare professional before beginning, modifying, or continuing any exercise program.
                  </p>
                </div>
              </section>

              {/* 3 */}
              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">3. User Accounts</h2>
                <p className="text-gray-700 mb-4">
                  Ghost Workout uses Sign in with Apple (iOS) or Google Sign-In (Android) for authentication, managed through Firebase Auth. We do not store or manage passwords directly. You are responsible for the security of your linked Apple or Google account.
                </p>
                <p className="text-gray-700">
                  You are responsible for all activity that occurs under your account. You must notify us immediately at <span className="font-medium">support@hellofavors.com</span> if you become aware of any unauthorized use of your account.
                </p>
              </section>

              {/* 4 */}
              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">4. Location Data and GPS Tracking</h2>
                <p className="text-gray-700 mb-4">
                  Outdoor workout recording requires access to your device's location services. By using GPS-based features, you consent to collection of precise GPS coordinates during active workout sessions, storage of GPS routes on our servers, and — on iOS — background location updates while an active workout is in progress (disabled when the workout ends).
                </p>
                <p className="text-gray-700">
                  We do not track your location when the app is not actively recording a workout. You can control location permissions through your device settings. Disabling location access prevents GPS-based workout recording; indoor pedometer-based workouts remain available.
                </p>
              </section>

              {/* 5 */}
              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">5. Subscriptions and In-App Purchases</h2>
                <p className="text-gray-700 mb-4">
                  Core ghost comparison features are free. A premium subscription unlocks AI Reflection. Subscriptions are offered exclusively through in-app purchase via the Apple App Store (iOS) or Google Play Store (Android). Ghost Workout does not directly collect or store your payment card or billing details.
                </p>
                <p className="text-gray-700 mb-4">
                  All subscription billing, auto-renewal, payment processing, cancellation, and refunds are governed by Apple's or Google's terms and policies. To cancel your subscription or request a refund, use the subscription management tools provided by Apple (Settings → [Your Name] → Subscriptions) or Google (Google Play → Subscriptions). Deleting the app does not cancel an active subscription.
                </p>
                <p className="text-gray-700">
                  We reserve the right to change subscription pricing or features with reasonable advance notice.
                </p>
              </section>

              {/* 6 */}
              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">6. Premium AI Reflection</h2>
                <p className="text-gray-700 mb-4">
                  Premium subscribers may request an AI-generated reflection after completing a workout. This feature sends a structured workout summary (activity type, tracking method, duration, distance, pace, ghost outcome, and a brief comparison history) to a third-party AI provider (Anthropic). No raw GPS coordinates are transmitted. Reflections are generated on demand and returned to your device; we do not store generated reflection text on our servers.
                </p>
                <div className="bg-amber-50 border-l-4 border-amber-400 p-4">
                  <p className="text-amber-800">
                    <span className="font-semibold">AI Reflection Disclaimer:</span> AI Reflection outputs are generated by a large language model and may be incomplete, inaccurate, or otherwise imperfect. They are provided for informational and motivational purposes only and do not constitute medical, coaching, nutritional, or professional advice of any kind. You remain solely responsible for your training decisions. Do not rely on AI Reflection output for health or safety decisions; consult a qualified professional for any medical or training concern.
                  </p>
                </div>
              </section>

              {/* 7 */}
              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">7. Assumption of Risk</h2>
                <div className="bg-red-50 border-l-4 border-red-400 p-4 mb-4">
                  <p className="text-red-800 font-semibold mb-2">Please read this section carefully.</p>
                  <p className="text-red-800">
                    Physical exercise, including running and walking, involves inherent risk of injury, illness, or death. By using Ghost Workout, you voluntarily assume all risks associated with your exercise activities, including but not limited to: physical exertion; cardiovascular or musculoskeletal injury; falls; adverse weather conditions; traffic; terrain hazards; navigation errors; and conditions at locations you choose to exercise.
                  </p>
                </div>
                <p className="text-gray-700 mb-4">
                  You are solely responsible for:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-gray-700">
                  <li>Assessing your own fitness level and health before exercising</li>
                  <li>Choosing safe routes and conditions for your workouts</li>
                  <li>Exercising within your physical limits and stopping if you experience pain or discomfort</li>
                  <li>Complying with all applicable laws, including traffic regulations, when exercising in public spaces</li>
                  <li>Not relying on the app for real-time safety decisions (e.g., navigation in traffic)</li>
                </ul>
                <p className="text-gray-700 mt-4">
                  Ghost Workout is not responsible for any injury, illness, accident, property damage, or loss of life arising from your exercise activities, to the fullest extent permitted by applicable law.
                </p>
              </section>

              {/* 8 */}
              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">8. Accuracy Limitations</h2>
                <p className="text-gray-700 mb-4">
                  Ghost Workout uses GPS, device sensors, and algorithmic estimation to generate workout metrics. You acknowledge that:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-gray-700">
                  <li>GPS coordinates, distance, pace, and elevation data may be approximate and subject to error based on device hardware, satellite signal quality, environmental conditions, and other factors</li>
                  <li>Indoor and pedometer-based distance is an estimation derived from step count and stride-length models; it is not a precise measurement and may differ materially from actual distance</li>
                  <li>Ghost comparison matching, route overlap detection, and ghost timing data are approximate and may not exactly reflect actual performance differences</li>
                  <li>Workout metrics should not be relied upon where precision is critical (e.g., medical monitoring, competition timing, navigation in hazardous conditions)</li>
                </ul>
              </section>

              {/* 9 */}
              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">9. Content and Data Ownership</h2>
                <p className="text-gray-700 mb-4">
                  You retain ownership of your workout data and GPS routes. By using the Service, you grant Hello Favors, LLC a worldwide, non-exclusive, royalty-free license to store, process, and sync your data to provide the Service, and to use anonymized, aggregated data to improve the Service. We do not sell your personal workout data to third parties.
                </p>
              </section>

              {/* 10 */}
              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">10. Prohibited Uses</h2>
                <p className="text-gray-700 mb-4">You agree not to use Ghost Workout to:</p>
                <div className="bg-red-50 border border-red-200 rounded-lg p-4">
                  <ul className="list-disc pl-6 space-y-2 text-red-800">
                    <li>Violate any applicable laws or regulations</li>
                    <li>Interfere with or disrupt our services, servers, or networks</li>
                    <li>Access other users' accounts or data without authorization</li>
                    <li>Upload false, misleading, or harmful information</li>
                    <li>Use the Service for commercial purposes without our written authorization</li>
                    <li>Reverse-engineer, decompile, or attempt to derive source code from the Service</li>
                    <li>Attempt to bypass or circumvent our security measures or subscription entitlement checks</li>
                  </ul>
                </div>
              </section>

              {/* 11 */}
              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">11. Disclaimer of Warranties</h2>
                <p className="text-gray-700 mb-4 uppercase font-semibold text-sm">
                  To the fullest extent permitted by applicable law:
                </p>
                <p className="text-gray-700 mb-4">
                  THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. HELLO FAVORS, LLC EXPRESSLY DISCLAIMS ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, ACCURACY, AND RELIABILITY.
                </p>
                <p className="text-gray-700 mb-4">
                  We do not warrant that: (a) the Service will be uninterrupted, error-free, or always available; (b) workout tracking, GPS data, pedometer data, or ghost comparison results will be accurate or complete; (c) any defects in the Service will be corrected; or (d) the Service or its servers are free of viruses or other harmful components.
                </p>
                <p className="text-gray-700">
                  Some jurisdictions do not allow the exclusion of implied warranties. If applicable law prohibits the disclaimer above, it applies to the maximum extent permitted.
                </p>
              </section>

              {/* 12 */}
              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">12. Limitation of Liability</h2>
                <p className="text-gray-700 mb-4 uppercase font-semibold text-sm">
                  To the fullest extent permitted by applicable law:
                </p>
                <p className="text-gray-700 mb-4">
                  IN NO EVENT SHALL HELLO FAVORS, LLC, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING WITHOUT LIMITATION: LOSS OF DATA; PHYSICAL INJURY OR DEATH ARISING FROM FITNESS ACTIVITIES; DECISIONS MADE BASED ON AI REFLECTION OUTPUTS; INACCURACIES IN GPS, PEDOMETER, OR GHOST COMPARISON DATA; SERVICE DISRUPTIONS; OR ANY OTHER INTANGIBLE LOSS — EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
                </p>
                <p className="text-gray-700 mb-4">
                  HELLO FAVORS, LLC'S TOTAL CUMULATIVE LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THE SERVICE OR THESE TERMS SHALL NOT EXCEED THE GREATER OF: (A) THE TOTAL AMOUNTS YOU HAVE PAID TO GHOST WORKOUT THROUGH IN-APP PURCHASES IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE CLAIM; OR (B) ONE HUNDRED DOLLARS (USD $100).
                </p>
                <p className="text-gray-700">
                  Some jurisdictions do not allow the exclusion or limitation of certain damages. In such jurisdictions, our liability is limited to the maximum extent permitted by law.
                </p>
              </section>

              {/* 13 */}
              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">13. Indemnification</h2>
                <p className="text-gray-700">
                  You agree to indemnify, defend, and hold harmless Hello Favors, LLC and its officers, directors, employees, agents, and successors from any claims, liabilities, damages, losses, costs, and expenses (including reasonable attorneys' fees) arising from or related to: (a) your use of the Service in violation of these Terms; (b) your violation of any applicable law or the rights of any third party; or (c) data or content you submit to the Service.
                </p>
              </section>

              {/* 14 */}
              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">14. Termination and Account Deletion</h2>
                <p className="text-gray-700 mb-4">
                  We may suspend or terminate your access to the Service at any time, without prior notice, for any violation of these Terms, suspected fraud or abuse, security concerns, or unlawful use.
                </p>
                <div className="bg-blue-50 border-l-4 border-blue-400 p-4 mb-4">
                  <p className="text-blue-800 font-medium mb-2">Deleting your account</p>
                  <p className="text-blue-800">
                    You may delete your account at any time from within the mobile app: <span className="font-medium">Settings → Delete Account</span>. You may also visit <Link to="/delete-account" className="underline font-medium">ghostworkout.com/delete-account</Link> or email <span className="font-medium">privacy@hellofavors.com</span>. See our <Link to="/privacy-policy" className="underline">Privacy Policy</Link> for details on data deletion and retention.
                  </p>
                </div>
                <p className="text-gray-700">
                  Deleting the app does not delete your account or cancel an active subscription. Cancel your subscription through the applicable app store before or after deleting your account.
                </p>
              </section>

              {/* 15 */}
              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">15. Governing Law and Venue</h2>
                <p className="text-gray-700 mb-4">
                  These Terms are governed by the laws of the State of California, United States, without regard to its conflict-of-law provisions, except where applicable mandatory law requires otherwise.
                </p>
                <p className="text-gray-700">
                  Any action or proceeding arising out of or relating to these Terms or the Service shall be brought exclusively in the state or federal courts located in Santa Clara County, California, and you hereby consent to the personal jurisdiction of those courts and waive any objection to venue in those courts.
                </p>
              </section>

              {/* 16 */}
              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">16. General Provisions</h2>
                <ul className="list-disc pl-6 space-y-3 text-gray-700">
                  <li><span className="font-semibold">Entire Agreement.</span> These Terms, together with our Privacy Policy, constitute the entire agreement between you and Hello Favors, LLC regarding the Service and supersede all prior agreements or understandings.</li>
                  <li><span className="font-semibold">Severability.</span> If any provision of these Terms is found to be invalid, illegal, or unenforceable, that provision will be modified to the minimum extent necessary to make it enforceable, and the remaining provisions will continue in full force.</li>
                  <li><span className="font-semibold">No Waiver.</span> Our failure to enforce any right or provision of these Terms will not constitute a waiver of that right or provision.</li>
                  <li><span className="font-semibold">Assignment.</span> You may not assign or transfer these Terms or your rights hereunder without our prior written consent. We may assign our rights and obligations under these Terms without restriction.</li>
                  <li><span className="font-semibold">Force Majeure.</span> We will not be liable for any failure or delay in performance resulting from causes beyond our reasonable control, including acts of God, natural disasters, infrastructure outages, or third-party service failures.</li>
                </ul>
              </section>

              {/* 17 */}
              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">17. Changes to Terms</h2>
                <p className="text-gray-700">
                  We may modify these Terms at any time. Material changes will be communicated through in-app notifications or by updating the "Last Updated" date on this page with at least 30 days' notice where required. Your continued use of the Service after changes take effect constitutes your acceptance of the revised Terms.
                </p>
              </section>

              {/* 18 */}
              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">18. Contact Information</h2>
                <p className="text-gray-700 mb-4">
                  If you have questions about these Terms, please contact us:
                </p>
                <div className="bg-gray-50 p-6 rounded-lg">
                  <ul className="space-y-3 text-gray-700">
                    <li className="flex items-center">
                      <span className="w-20 font-semibold">Email:</span>
                      <span>legal@hellofavors.com</span>
                    </li>
                    <li className="flex items-start">
                      <span className="w-20 font-semibold">Mail:</span>
                      <span>Hello Favors, LLC<br />6469 Almaden Expy. Ste 80 #362<br />San Jose, CA 95120</span>
                    </li>
                  </ul>
                </div>
              </section>

            </div>
          </div>
        </div>

        <div className="mt-8 text-center">
          <Link to="/privacy-policy" className="text-blue-600 hover:text-blue-800 font-medium">
            View Privacy Policy
          </Link>
        </div>
      </div>
    </div>
  );
};

export default GhostWorkoutTerms;
